# Example compose file for Apache Tomcat

version: '3.2'

services:
  appserver:
    image: bcv-tomcat:9.0.41-r0
    container_name: appserver
    ports:
      - 8009:8009
      - 8080:8080
    hostname: appserver
    environment:
      - JAVA_XMS=768M
      - JAVA_XMX=1536M
      - TZ=Europe/Prague
      - DOCKER_TOMCAT_ENABLE_AJP=
#      - DOCKER_TOMCAT_DISABLE_ACCESS_LOG=
#      - DOCKER_TOMCAT_AJP_PASSFILE=/run/secrets/ajp.pwfile
#    volumes:
#      - type: bind
#        source: ./tomcat_ajp.pwfile
#        target: /run/secrets/ajp.pwfile
#        read_only: true
#      - type: bind
#        source: ./certs
#        target: /opt/tomcat/truststore/certs
#        read_only: true
